import { fontFamily } from "html2canvas/dist/types/css/property-descriptors/font-family"
import { Qwitcher_Grypen, Aladin, Questrial, ABeeZee, Parisienne } from "next/font/google"
const qwitcherGrypenFont = Qwitcher_Grypen({ subsets: ['latin'], weight:['400']});
const aladinFont = Aladin({subsets: ['latin-ext'], weight: ['400'] })
const questrial = Questrial({subsets: ['latin'], weight: ['400']})
const aBeeZee = ABeeZee({subsets:['latin'], weight:['400']})
const greatVibes  = Parisienne({subsets:['latin'], weight:['400']})
const chunky = '"font-chunky"'
export const PRODUCT_PRICES = {
  material: {
    silicone: 0,
    polycarbonate: 5_00,
  },
  finish: {
    smooth: 0,
    textured: 3_00,
  },
} as const

export const BASE_PRICE = 29_00

export const products = [
  {
    id: 0,
    title: "1 Picture - Custom iPhone Case",
    description: "This is the description for Product 1",
    imageUrl: "/product-1.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: qwitcherGrypenFont.className,
    fontname2: aladinFont.className,
    font1Size: '30px',
    font2Size: '30px',
    placeholderText1: "Feeling Blue",
    placeholderText2: "Chidi Eze",
    frameX: 300,
    frameY: 250,
    assetimage:  "",
    assetimagePosition: "",
    assetimageHeight:50,
    assetimageWidth:90,
    rounded: "",
    isText: true,
    text1Position: 'bottom-[318px]',
    text2Position: 'bottom-[300px]',
    text2PositionLeft: '',
    text1Color: 'text-white placeholder:text-white',
    text2Color: 'text-white placeholder:text-white',
    isRnd: true,
    top: 'top-[180px]',
    left: 'left-[30px]',
    setImageWidth: 180,
    setImageHeight: 250,
    colorOptions1: '/product1/red.png',
    colorOptions2: '/product1/blue.png',
    colorOptions3: '/product1/green.png',
    colorOptions4: '/product1/black.png',
  },
  {
    id: 1,
    title: "Feel the Music - Custom iPhone Case",
    description: "This is the description for Product 2",
    imageUrl: "/product-2.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: questrial.className,
    fontname2: questrial.className,
    font1Size: '18px',
    font2Size: '12px',
    placeholderText1: "Feeling Blue",
    placeholderText2: "Chidi Eze",
    frameX: 9 / 12,
    frameY: 250,
    assetimage:  "/music.png",
    assetimagePosition:"bottom-[12px]",
    assetimageHeight:260,
    assetimageWidth:260,
    rounded: 'rounded-t-[80px]',
    isText: true,
    text1Position: 'bottom-[330px] text-center',
    text2Position: 'bottom-[312px]',
    text2PositionLeft: '',
    text1Color: 'text-white placeholder:text-white',
    text2Color: 'text-white placeholder:text-white',
    isRnd: false,
    top: 'top-[193px]',
    left: 'left-[13px]',
    setImageWidth: 214,
    setImageHeight: 950,
    colorOptions1: '/product1/black.png',
    colorOptions2: '/product1/blue.png',
    colorOptions3: '/product1/rose.png',
    colorOptions4: '/product1/green.png',
  },
  {
    id: 2,
    title: "Beach Memories - Custom iPhone Case",
    description: "This is the description for Product 3",
    imageUrl: "/product-3.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: qwitcherGrypenFont.className,
    fontname2: qwitcherGrypenFont.className,
    font1Size: '28px',
    font2Size: '40px',
    placeholderText1: "Beach Vibe",
    placeholderText2: "10/13",
    frameX: 9 / 12,
    frameY: 250,
    assetimage:  "/summer.png",
    assetimagePosition:"left-[80px] filter grayscale-1 top-[410px] rounded-[35px]",
    assetimageHeight:50,
    assetimageWidth:90,
    rounded: "inset-0 -rotate-3 shadow-xl border-solid border-t-[10px] border-l-[10px] border-r-[10px] border-b-[45px] border-[#e5ebea]",
    isText: true,
    text1Position: 'top-[348px] -rotate-3 ',
    text2Position: 'top-[332px]',
    text2PositionLeft: 'left-[105px]',
    text1Color: 'text-red-600 placeholder:text-red-600',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    top: 'top-[125px]',
    left: 'left-[30px]',
    setImageWidth: 180,
    setImageHeight: 250,
    colorOptions1: '/product2/black.png',
    colorOptions3: '/product2/red.png',
    colorOptions2: '/product2/blue.png',
    colorOptions4: '/product2/green.png',
  },
  {
    id: 3,
    title: "Flowery Season - Custom iPhone Case",
    description: "This is the description for Product 3",
    imageUrl: "/product-4.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: greatVibes.className,
    fontname2: aBeeZee.className,
    font1Size: '16px',
    font2Size: '8px',
    placeholderText1: "My memories",
    placeholderText2: "19.05.24",
    frameX: 4 / 5,
    frameY: 250,
    assetimage:  "/tape.png",
    assetimagePosition:"top-[150px] left-[64px]",
    assetimageHeight:50,
    assetimageWidth:90,
    rounded: "inset-0  shadow-xl border-solid border-t-[6px] border-l-[6px] border-r-[6px] border-b-[45px] border-[#fcf7e8] bg-white/20 backdrop-blur-lg rounded-lg border-white/20",
    isText: true,
    text1Position: 'bottom-[89px] left-[66px]',
    text2Position: 'bottom-[77px]',
    text2PositionLeft: 'left-[80px]',
    text1Color: 'text-black/70 placeholder:text-black/70',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    top: 'top-[160px] ',
    left: 'left-[30px]',
    setImageWidth: 180,
    setImageHeight: 250,
    colorOptions1: '/product3/black.png',
    colorOptions2: '/product3/blue.png',
    colorOptions3: '/product3/rose.png',
    colorOptions4: '/product3/green.png',
    
  },
  {
    id: 4,
    title: "Flowery Season - Custom iPhone Case",
    description: "This is the description for Product 3",
    imageUrl: "/product-4.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: chunky,
    fontname2: aBeeZee.className,
    font1Size: '16px',
    font2Size: '8px',
    placeholderText1: "My memories",
    placeholderText2: "19.05.24",
    frameX: 4 / 5,
    frameY: 250,
    assetimage:  "/product4/hearts.png",
    assetimagePosition:"",
    assetimageHeight:200,
    assetimageWidth:300,
    rounded: "inset-0 shadow-xl border-solid border-t-[6px] border-l-[6px] border-r-[6px] border-b-[25px] border-[#fcf7e8]",
    isText: true,
    text1Position: 'top-[20px] left-[66px]',
    text2Position: 'bottom-[77px]',
    text2PositionLeft: 'left-[80px]',
    text1Color: 'text-orange-300 placeholder:text-orange-300',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    top: 'top-[150px] ',
    left: 'left-[30px]',
    setImageWidth: 165,
    setImageHeight: 180,
    colorOptions1: '/product4/black.png',
    colorOptions2: '/product4/black.png',
    colorOptions3: '/product4/black.png',
    colorOptions4: '/product4/black.png',
    
  },
] as const
