import { fontFamily } from "html2canvas/dist/types/css/property-descriptors/font-family"
import { Qwitcher_Grypen, Aladin, Questrial, ABeeZee, Parisienne } from "next/font/google"
const qwitcherGrypenFont = Qwitcher_Grypen({ subsets: ['latin'], weight: ['400']});
const aladinFont = Aladin({subsets: ['latin-ext'], weight: ['400'] })
const questrial = Questrial({subsets: ['latin'], weight: ['400']})
const aBeeZee = ABeeZee({subsets:['latin'], weight:['400']})
const greatVibes  = Parisienne({subsets:['latin'], weight:['400']})
const chunky = 'font-chunky'
const season = 'font-season'
const seasonIT = 'font-seasonIT'


export interface Product {
  id: number;
  requiresImage: boolean;
  title: string;
  description: string;
  category: {
    device: string;
    customize: string;
    magsafe: boolean;
    collection: string;
    theme: string;
  };
  imageUrl: string;
  price: string;
  discountedPrice: string;
  fontname: string;
  fontname2?: string;
  frameX: number;
  frameY: number;
  rounded: string;
  deviceSeries: string[];
  devices: string[];
  caseType: string[];
  customization: string[];
  designColour: string[];
}
export const PRODUCT_PRICES = {
  material: {
    silicone: 0,
    polycarbonate: 5_00,
  },
  finish: {
    smooth: 0,
    textured: 3_00,
  },
} as const

export const BASE_PRICE = 29_00

export const products = [
  {
    id: 0,
    requiresImage: true,
    title: "Personalised Single Photo iPhone Case",
    description: "This is the description for Product 1",
    category: {device: 'iphone', customize: 'picture-only', magsafe: true, collection: 'picture-cases', theme: '1-picture'  },
    productsimg1: '/product0/product-img-1.png', 
    productsimg2: '/product0/product-img-2.png', 
    productsimg3: '/product0/product-img-3.png', 
    productsimg4: '/product0/product-1-3d-model.glb', 
    posterimg3d: '/product0/poster-1.webp',
    imageUrl: "/product-1.png",
    isImage2: false,
    price: "32.0$",
    discountedPrice: "19.9$",
    isFrame: false,
    fontname2: season,
    fontname: seasonIT,
    font1Size: '30px',
    font2Size: '30px',
    placeholderText1: "Julia",
    placeholderText2: "& Robin",
    frameX: 9 / 16,
    frameY: 250,
    assetimage:  "",
    assetimagePosition: "",
    assetimageHeight:50,
    assetimageWidth:90,
    rounded: "rounded-[80px]",
    isText: false,
    isText2: false,
    isModel: true,
    isAsset: false,
    isImage: true,
    text1Position: 'italic !font-[200] top-[350px] text-center',
    text2Position: 'font-[100] top-[380px]',
    text2PositionLeft: '',
    text1Color: 'text-white placeholder:text-white',
    text2Color: 'text-white placeholder:text-white',
    isRnd: false,
    needsFill: true,
    top: false,
    left: false,
    setImageWidth: 200,
    setImageHeight: 900,
    colorOptions1: '',
    colorOptions2: '',
    colorOptions3: '',
    colorOptions4: '',

    deviceSeries: ['iphone 13'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['picture-&-text'],
    designColour: ['white']
  },
  {
    id: 1,
    requiresImage: true,
    title: "Personalised Love Kiss Polaroid iPhone Case",
    description: "This is the description for Product 3",
    category: {device: 'iphone', customize: 'picture-&-text', magsafe: true, collection: 'polaride', theme: 'flowery'  },
    productsimg1: '/product1/product-img-1.png', 
    productsimg2: '/product1/product-img-2.png', 
    productsimg3: '/product1/product-img-3.png', 
    productsimg4: '/product1/product-4-img-3d.glb', 
    posterimg3d: '/product1/poster-2.webp',
    imageUrl: "/product-6.png",
    imageUrl2: '',
    price: "32.0$",
    discountedPrice: "19.9$",
    isFrame: false,
    fontname: chunky,
    fontname2: aBeeZee.className,
    font1Size: '16px',
    font2Size: '12px',
    placeholderText1: "focus on the goods",
    placeholderText2: "the less you care the happier you will be",
    frameX: 4 / 5,
    frameY: 250,
    assetimage:  "/product4/kiss.png",
    assetimagePosition:"",
    assetimageHeight:200,
    assetimageWidth:300,
    rounded: "inset-0 shadow-xl border-solid border-t-[6px] border-l-[6px] border-r-[6px] border-b-[25px] border-[#fcf7e8]",
    isText: true,
    isText2: true,
    isModel: true,
    isAsset: true,
    isImage: true,
    text1Position: 'top-[20px] left-[88px] w-[100px]',
    text2Position: 'bottom-[60px] !bg-[#fcf7e8]/70 w-[180px]',
    text2PositionLeft: 'left-[0px]',
    text1Color: 'text-orange-300 placeholder:text-pink-500/80',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    needsFill: false,
    top: 'top-[150px] ',
    left: 'left-[30px]',
    setImageWidth: 165,
    setImageHeight: 180,
    colorOptions1: '/product5/black.png',
    colorOptions2: '/product5/blue.png',
    colorOptions3: '/product5/rose.png',
    colorOptions4: '/product5/green.png',

    deviceSeries: ['iphone 13'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['picture-&-text'],
    designColour: ['white']
  },
  
  {
    id: 2,
    requiresImage: true,
    title: "Beach Memories Photo Polaroid iPhone Case",
    description: "This is the description for Product 3",
    category: {device: 'iphone', customize: 'picture-&-text', magsafe: true, collection: 'polaride', theme: 'summer'  },
    productsimg1: '/product2/product-img-1.png', 
    productsimg2: '/product2/product-img-2.png', 
    productsimg3: '/product2/product-img-3.png', 
    productsimg4: '/product2/product-2-img-3d.glb', 
    posterimg3d: '/product2/poster.webp',
    imageUrl: "/product2/product-2-1.png",
    imageUrl2: "/product-1.png",
    price: "32.0$",
    discountedPrice: "32.9$",
    isFrame: false,
    fontname: qwitcherGrypenFont.className,
    fontname2: qwitcherGrypenFont.className,
    font1Size: '28px',
    font2Size: '40px',
    placeholderText1: "Beach Vibe",
    placeholderText2: "10/13",
    frameX: 9 / 12,
    frameY: 250,
    assetimage:  "/summer.png",
    assetimagePosition:"left-[80px] filter grayscale-1 top-[410px] rounded-[35px]",
    assetimageHeight:50,
    assetimageWidth:90,
    rounded: "inset-0 -rotate-3 shadow-xl border-solid border-t-[10px] border-l-[10px] border-r-[10px] border-b-[45px] border-[#e5ebea]",
    isText: true,
    isText2: true,
    isModel: true,
    isAsset: true,
    isImage: true,
    text1Position: 'top-[348px] -rotate-3 left-[50px]',
    text2Position: 'top-[332px]',
    text2PositionLeft: 'left-[105px]',
    text1Color: 'text-red-600 placeholder:text-red-600',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    needsFill: false,
    top: 'top-[125px]',
    left: 'left-[30px]',
    setImageWidth: 180,
    setImageHeight: 250,
    colorOptions1: '/product2/black.png',
    colorOptions3: '/product2/red.png',
    colorOptions2: '/product2/blue.png',
    colorOptions4: '/product2/green.png',

    deviceSeries: ['iphone 12'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['picture-&-text'],
    designColour: ['white']
  },
  {
    id: 3,
    requiresImage: true,
    title: "Arylic Flowery Painting Photo iPhone case",
    description: "This is the description for Product 3",
    category: {device: 'iphone', customize: 'picture-&-text', magsafe: true, collection: 'polaride', theme: 'flowery'  },
    productsimg1: '/product3/product-img-1.png', 
    productsimg2: '/product3/product-img-2.png', 
    productsimg3: '/product3/product-img-3.png', 
    productsimg4: '/product3/product-3-img-3d.glb', 
    posterimg3d: '/product3/poster.webp',
    imageUrl: "/product3/product-1.png",
    imageUrl2: "/product-1.png",
    price: "32.0$",
    discountedPrice: "32.9$",
    isFrame: false,
    fontname: greatVibes.className,
    fontname2: aBeeZee.className,
    font1Size: '20px',
    font2Size: '8px',
    placeholderText1: "My memories",
    placeholderText2: "19.05.24",
    frameX: 4 / 5,
    frameY: 250,
    assetimage:  "/tape.png",
    assetimagePosition:"top-[150px] left-[64px]",
    assetimageHeight:50,
    assetimageWidth:90,
    rounded: "inset-0  shadow-xl border-solid border-t-[6px] border-l-[6px] border-r-[6px] border-b-[45px] border-[#fcf7e8] bg-white/20 backdrop-blur-lg rounded-lg border-white/20",
    isText: true,
    isText2: true,
    isModel: true,
    isAsset: true,
    isImage: true,
    text1Position: 'bottom-[-8px] left-[60px]',
    text2Position: 'bottom-[62px]',
    text2PositionLeft: 'left-[84px]',
    text1Color: 'text-black/70 placeholder:text-black/70',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    needsFill: false,
    top: 'top-[160px] ',
    left: 'left-[30px]',
    setImageWidth: 180,
    setImageHeight: 250,
    colorOptions1: '/product3/black.png',
    colorOptions2: '/product3/blue.png',
    colorOptions3: '/product3/rose.png',
    colorOptions4: '/product3/green.png',

    deviceSeries: ['iphone 12'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['picture-&-text'],
    designColour: ['pink']
    
  },
  {
    id: 4,
    requiresImage: true,
    title: "Personalised Love Heart Polaroid iPhone Case",
    description: "This is the description for Product 3",
    category: {device: 'iphone', customize: 'picture-&-text', magsafe: true, collection: 'polaride', theme: 'flowery'  },
    productsimg1: '/product4/product-1-img.png', 
    productsimg2: '/product4/product-2-img.png', 
    productsimg3: '/product4/product-4-img.png', 
    productsimg4: '/product4/product-4-img-3d.glb',
    posterimg3d: '/product4/poster.webp', 
    imageUrl: "/product4/product-4-1.png",
    imageUrl2: "/product-1.png",
    price: "32.0$",
    discountedPrice: "19.9$",
    isFrame: false,
    fontname: chunky,
    fontname2: aBeeZee.className,
    font1Size: '16px',
    font2Size: '12px',
    placeholderText1: "focus on the goods",
    placeholderText2: "the less you care the happier you will be",
    frameX: 4 / 5,
    frameY: 250,
    assetimage:  "/product4/hearts1.png",
    assetimagePosition:"",
    assetimageHeight:200,
    assetimageWidth:300,
    rounded: "inset-0 shadow-xl border-solid border-t-[6px] border-l-[6px] border-r-[6px] border-b-[25px] border-[#fcf7e8]",
    isText: true,
    isText2: true,
    isModel: true,
    isAsset: true,
    isImage: true,
    text1Position: 'top-[20px] left-[88px] w-[100px]',
    text2Position: 'bottom-[60px] !bg-[#fcf7e8]/70 w-[180px]',
    text2PositionLeft: 'left-[0px]',
    text1Color: 'text-black placeholder:text-white',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    needsFill: false,
    top: 'top-[150px] ',
    left: 'left-[30px]',
    setImageWidth: 165,
    setImageHeight: 180,
    colorOptions1: '/product4/black.png',
    colorOptions2: '/product4/blue.png',
    colorOptions3: '/product4/rose.png',
    colorOptions4: '/product4/green.png',

    deviceSeries: ['iphone 13'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['picture-&-text'],
    designColour: ['pink']
  },
  {
    id: 5,
    requiresImage: true,
    title: "Feel the Music Photo iPhone Case",
    description: "This is the description for Product 2",
    category: {device: 'iphone', customize: 'picture-&-text', magsafe: true, collection: 'polaride', theme: 'music'  },
    productsimg1: '/product5/product-2-img.png', 
    productsimg2: '/product5/product-3-img.png', 
    productsimg3: '/product5/product-1-img.png', 
    productsimg4: '/product5/product-5-img-3d.glb',
    posterimg3d: '/product5/poster.webp', 
    imageUrl: "/product5/product-5-1.png",
    imageUrl2: "/product-1.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: questrial.className,
    fontname2: questrial.className,
    font1Size: '18px',
    font2Size: '12px',
    placeholderText1: "Feeling Blue",
    placeholderText2: "Chidi Eze",
    frameX: 9 / 12,
    frameY: 250,
    assetimage:  "/music.png",
    assetimagePosition:"bottom-[12px]",
    assetimageHeight:260,
    assetimageWidth:260,
    rounded: 'rounded-[25px] border-[5px] border-[#fff/50] opacity-[96%]',
    isText: true,
    isText2: true,
    isModel: true,
    isAsset: true,
    isImage: true,
    text1Position: 'bottom-[238px] text-center',
    text2Position: 'bottom-[282px]',
    text2PositionLeft: '',
    text1Color: 'text-white placeholder:text-white',
    text2Color: 'text-white placeholder:text-white',
    isRnd: false,
    needsFill: false,
    top: 'top-[213px]',
    left: 'left-[25px]',
    setImageWidth: 190,
    setImageHeight: 190,
    colorOptions1: '/product5/black.png',
    colorOptions2: '/product5/blue.png',
    colorOptions3: '/product5/rose.png',
    colorOptions4: '/product5/green.png',

    deviceSeries: ['iphone 13'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['picture-&-text'],
    designColour: ['white']
  },  
  {
    id: 6,
    requiresImage: true,
    title: "Flowery Season",
    description: "This is the description for Product 3",
    category: {device: 'iphone', customize: 'picture-&-text', magsafe: true, collection: 'polaride', theme: 'flowery'  },
    productsimg1: '/product-img-1.png', 
    productsimg2: '/product-img-1.png', 
    productsimg3: '/product-img-1.png', 
    productsimg4: '/product-img-1.png',
    posterimg3d: '', 
    imageUrl: "/product-7.png",
    imageUrl2: "/product-1.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: chunky,
    fontname2: aBeeZee.className,
    font1Size: '16px',
    font2Size: '12px',
    placeholderText1: "focus on the goods",
    placeholderText2: "the less you care the happier you will be",
    frameX: 4 / 5,
    frameY: 250,
    assetimage:  "/product4/butterfly.png",
    assetimagePosition:"",
    assetimageHeight:200,
    assetimageWidth:300,
    rounded: "inset-0 shadow-xl border-solid border-t-[6px] border-l-[6px] border-r-[6px] border-b-[25px] border-[#fcf7e8]",
    isText: true,
    isText2: true,
    isModel: true,
    isAsset: true,
    isImage: true,
    text1Position: 'top-[20px] left-[88px] w-[100px]',
    text2Position: 'bottom-[60px] !bg-[#fcf7e8]/70 w-[180px]',
    text2PositionLeft: 'left-[0px]',
    text1Color: 'text-orange-300 placeholder:text-pink-500/80',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    needsFill: false,
    top: 'top-[150px] ',
    left: 'left-[30px]',
    setImageWidth: 165,
    setImageHeight: 180,
    colorOptions1: '/product6/black.png',
    colorOptions2: '/product6/blue.png',
    colorOptions3: '/product6/rose.png',
    colorOptions4: '/product6/green.png',

    deviceSeries: ['iphone 12'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['picture-&-text'],
    designColour: ['pink']
  },
  {
    id: 7,
    requiresImage: true,
    title: "Flowery Season",
    description: "This is the description for Product 3",
    category: {device: 'iphone', customize: 'none', magsafe: true, collection: 'leather', theme: 'dark'  },
    productsimg1: '/product-img-1.png', 
    productsimg2: '/product-img-1.png', 
    productsimg3: '/product-img-1.png', 
    productsimg4: '/product-img-1.png',
    posterimg3d: '', 
    imageUrl: "/product-8.png",
    imageUrl2: "/product-1.png",
    price: "32.0$",
    discountedPrice: "29.9$",
    isFrame: false,
    fontname: qwitcherGrypenFont.className,
    fontname2: aBeeZee.className,
    font1Size: '40px',
    font2Size: '12px',
    placeholderText1: "besty",
    placeholderText2: "the less you care the happier you will be",
    frameX: 4 / 4,
    frameY: 250,
    assetimage:  "/product7/travel.png",
    assetimagePosition:"!-z-[50]",
    assetimageHeight:200,
    assetimageWidth:300,
    rounded: "border-t-[8px] border-l-[8px] border-r-[8px] border-b-[30px] border-white",
    isText: true,
    isText2: false,
    isModel: true,
    isAsset: true,
    isImage: true,
    text1Position: 'top-[270px] left-[-25px] w-[100px] rotate-12',
    text2Position: '',
    text2PositionLeft: 'left-[0px]',
    text1Color: 'text-black placeholder:text-black',
    text2Color: 'text-black placeholder:text-black',
    isRnd: false,
    needsFill: false,
    top: 'top-[146px] rotate-12',
    left: 'left-[46px]',
    setImageWidth: 150,
    setImageHeight: 150,
    colorOptions1: '/product7/black.png',
    colorOptions2: '/product7/blue.png',
    colorOptions3: '/product7/rose.png',
    colorOptions4: '/product7/green.png',

    deviceSeries: ['iphone 12'], 
    devices: ['iphone'],
    caseType: ['polycarbonate'],
    customization: ['none'],
    designColour: ['3 color']
  },
] as const
